prefixes = {
    "rec":"Searching finished! Here are my recommendations:",
    "recfb":"OK, now I got a better idea! Here is my recommendations:",
    "prefb":"OK, do you have anything else to add before I recommend some food for you, such as flavor, cuisine?",
    "aftrec1":"Scroll up to check the two recommendations. Would you like to try any of them in the following days?",
    "aftrec2":"Please scroll up to check my recommendations. Now would you like to try any of them in the following days?",
    "fb":"Could you tell me why you don't like these foods? I'll try to refine the recommendation based on your input. Due to the token limitation, the next round will be the last-round of recommendations.",
    "end1":"I am glad that the recommendation works! Hope you enjoy the meal when you try it out!",
    "end2y":"I am glad you like my recommendation! Enjoy your meal when you try it out!",
    "end2n":"It seems like my recommendation skill needs some improvement, but thank you for your feedback. This is the end of the conversation.",
    "emo": "How are you feeling these days?",
    "eh": "Do you have a planned time for eating, or do you just eat when feeling hungry?",
    "time": "In general, how long do you set aside for each meal?",
    "env": "Do you prefer to eat at a restaurant or cook at home?",
    "his": "What are your typical meals?",
    "goal": "What do you hope to achieve through a healthy diet?",
}